### ISSUE TITLE
subprojects not displayed correctly in drop-down menu

### ISSUE THREAD

**Issue by int-red** [chiliproject-eu/chiliproject_look_and_feel#1]
I created a project with subprojects Project_A and Project_B.
In the Projects drop-down menu these are displayed distorted with leading garbage text:
&nbsp;&nbsp;&#187; Project_A
&nbsp;&nbsp;&#187; Project_B

**Comment by svoboda-jan** [comment]
Fixed in master.

You can download the latest version with the fix here:
https://github.com/chiliproject-eu/chiliproject_look_and_feel/archive/master.zip
