### ISSUE TITLE
How to Use this plugin

### ISSUE THREAD

**Issue by hello2jack** [chiliproject-eu/chiliproject_look_and_feel#3]
Hi i'm an Redmine user, could you please teach me how to use(install) this plugin on redmine?

**Comment by svoboda-jan** [comment]
Hello,

to install the plugin you just have to unzip the latest release to your redmine plugins directory, rename the folder to `chiliproject_look_and_feel` and restart the server.

Releases can be found here:
https://github.com/chiliproject-eu/chiliproject_look_and_feel/releases
