### ISSUE TITLE
user activity label doesn't show the title

### ISSUE THREAD

**Issue by bluenevus** [chiliproject-eu/chiliproject_look_and_feel#5]
see the image...it says missing translation and a bunch of other things beside the title

![2016-05-07 10_41_08-activity - icpccs - mdevops portal](https://cloud.githubusercontent.com/assets/3675043/15092740/861cb994-1440-11e6-8a46-a509ad7c03e0.png)

**Comment by svoboda-jan** [comment]
I can't see the `label_show_user_activity` in redmine locale files. Maybe it is caused by another redmine plugin.
